[project]
name = "studies"
version = "0.1.0"
description = ""
authors = [
    {name = "Quinn Herden", email = "55929299+QuinnHerden@users.noreply.github.com"},
]
dependencies = [
    "typer>=0.12.3",
    "genanki>=0.13.1",
    "toml>=0.10.2",
    "pydantic>=2.7.4",
    "pydantic-settings>=2.3.4",
    "dataclasses>=0.6",
    "python-frontmatter>=1.1.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "black>=24.4.2",
    "flake8>=7.1.0",
    "pytest>=8.2.2",
]

[tool.pdm.scripts]
start = "pdm run build"

fmt = "pdm run black ."

checks = {composite  = [
       "check-fmt",
       "test"
]}
check-fmt = "pdm run black --check ."
test = "pdm run pytest"

build = {composite = [
    'list_markdown',
    'load_markdown',
    'parse_markdown',
    'parse_html',
    'generate_deck',
]}

list_markdown = "pdm run python -m app.main decks list"
load_markdown  = "echo 'not implemented yet'"
parse_markdown = "echo 'not implemented yet'"
parse_html  = "echo 'not implemented yet'"
generate_deck = "echo 'not implemented yet'"
