name: Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deployment:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Run Build
        run: pdm build
      
      - name: Run Publish
        run: pdm publish --username --password
